services:
 web:
  build: .
  volumes:
   - .:/app
  ports:
   - "5000:5000"
  command: python /app/src/recommenderapp/app.py

 postgres:
  image: postgres:latest
  environment:
   - POSTGRES_USER= ${POSTGRES_USER}
   - POSTGRES_DB= ${POSTGRES_DB}
   - POSTGRES_PASSWORD=${POSTGRES_PW}
  ports:
   - "5432:5432"