services:
 web:
  build: .
  volumes:
   - .:/app
  ports:
   - "5000:5000"
  depends_on:
   postgres:
    condition: service_healthy
  command: python /app/src/recommenderapp/app.py

 postgres:
  image: postgres:latest
  environment:
   - POSTGRES_USER=${POSTGRES_USER}
   - POSTGRES_PASSWORD=${POSTGRES_PW}
   - POSTGRES_DB=${POSTGRES_DB}
  ports:
   - "5432:5432"
  healthcheck:
   test: ["CMD","pg_isready","-U","${POSTGRES_USER}"]
   interval: 10s
   timeout: 5s
   retries: 5

 pgadmin:
  container_name: pgadmin
  image: dpage/pgadmin4:latest
  environment:
   - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
   - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
  ports:
   - "5050:80"