name: Code Coverage

on: [push]

jobs:
  upload-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Replace '3.x' with your desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install pandas
          pip install -U Flask
          pip install -U flask-cors
          pip install docker
          pip install pytest
          pip install flask-bcrypt
          pip install pytest-mock
          pip install pytest-cov
          pip install numpy
          pip install pyjwt
          pip install werkzeug
          pip install flask-sqlalchemy
          pip install python env
          pip install psycopg2-binary

      - name: Run tests and generate coverage
        run: |
          cd test
          coverage run --source=test -m pytest test_*.py
          coverage xml -i

      - name: Upload coverage report to Codecov
        run: |
          bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}
