name: Unittest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install pandas
        pip install -U Flask
        pip install -U flask-cors
        pip install docker
        pip install pytest
        pip install flask-bcrypt
        pip install pytest-mock
        pip install pytest-cov
        pip install numpy
        pip install pyjwt
        pip install werkzeug
        pip install flask-sqlalchemy
        pip install python-dotenv
        pip install psycopg2-binary
    - name: Running test cases for restAPI
      run: pytest test/test_restAPI.py
    - name: Running test cases for predicting
      run: python test/test_predict.py
    - name: Running test cases for searching
      run: python test/test_search.py
    - name: Running test cases for util
      run: python test/test_util.py

    
